student:
  institute: ICET-DEV-TEAM
  batch: 103

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ institute_crm
    username: root
    password: akindu123

  jpa:
    hibernate:
       ddl-auto : create